### ISSUE TITLE
During training, an error occurred

### ISSUE THREAD

**Issue by song201216** [Xiefan-Guo/CTSDG#4]
Hello, author, I think your work is amazing, but when I started training, he made a mistake, I can't solve it temporarily, can you help me？ thank you!
Traceback (most recent call last):
  File "E:/code/CTSDG-main/train.py", line 102, in <module>
    train(opts, image_data_loader, generator, discriminator, extractor, generator_optim, discriminator_optim, is_cuda)
  File "E:\code\CTSDG-main\trainer.py", line 45, in train
    output, projected_image, projected_edge = generator(input_image, torch.cat((input_edge, input_gray_image), dim=1), mask)
  File "D:\Anaconda3\envs\torch18\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\code\CTSDG-main\models\generator\generator.py", line 248, in forward
    dc_texture = torch.cat((dc_texture, ec_textures[ec_texture_skip]), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 3 and 2 (The offending index is 0)

**Comment by 01SHENyankun** [comment]
你好，你复现出来了吗，能否指点一下
