### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by AndyVerne** [Xiefan-Guo/CTSDG#6]
```
python test.py --pre_trained ./checkpoints/places2.pt --image_root ./images/ --mask_root ./masks/ --result_root ./result/ --number_eval 1
```
Sorry to bother you in this way.
When I tried to test this project following the instruction in markdown,  this error shows up.

```
 Cuda is available
OrderedDict([('pre_trained', './checkpoints/places2.pt'),
             ('image_root', './images/'),
             ('mask_root', './masks/'),
             ('num_workers', 4),
             ('batch_size', 1),
             ('load_size', (256, 256)),
             ('sigma', 2.0),
             ('mode', 'test'),
             ('result_root', './result/'),
             ('number_eval', 1)])
start test...
  0%|                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    output, __, __ = generator(input_image, torch.cat((input_edge, input_gray_image), dim=1), mask)
  File "/root/anaconda3/envs/CTSDG/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/CTSDG/models/generator/generator.py", line 97, in forward
    ec_textures['ec_t_1'], ec_textures['ec_t_masks_1'] = self.ec_texture_1(ec_textures['ec_t_0'], ec_textures['ec_t_masks_0'])
  File "/root/anaconda3/envs/CTSDG/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/CTSDG/models/generator/pconv.py", line 103, in forward
    images, masks = self.conv(images, masks)
  File "/root/anaconda3/envs/CTSDG/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/CTSDG/models/generator/pconv.py", line 50, in forward
    padding=self.padding, dilation=self.dilation, groups=1)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 9, 256, 256] to have 3 channels, but got 9 channels instead
```

And I have no clue how to fix it.

**Comment by xiefan-guo** [comment]
Hi, this model uses _3-channels image_ and _1-channel mask_ by default, but it seems that you have __3-channels mask__.

**Comment by AndyVerne** [comment]
> Hi, this model uses _3-channels image_ and _1-channel mask_ by default, but it seems that you have **3-channels mask**.

okay, I got it. Thank you so much!
